name: edu_quest
title: Edu_Quest
description: Edu Quest is your smart study buddy designed to revolutionize your
  learning experience.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  dot_navigation_bar: ^1.0.2
  file_picker: ^6.1.1
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.12
  flutter_gemma: ^0.2.1
  flutter_markdown: ^0.7.3+1
  flutter_riverpod: ^2.4.10
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^4.2.1
  flutter_spinkit: ^5.2.0
  freezed_annotation: ^2.4.1
  go_router: ^11.1.3
  google_fonts: ^6.1.0
  hive: ^2.2.3
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.2.0
  lottie: ^3.0.0
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.4
  syncfusion_flutter_pdf: ^24.2.4
  syncfusion_flutter_pdfviewer: ^24.2.5
  url_launcher: ^6.1.14
  uuid: ^4.3.3
  internet_connection_checker: ^2.0.0
  permission_handler: ^11.2.0
  qr_code_dart_scan: ^0.9.1
  http: ^1.2.2
  html: ^0.15.4
  process_run: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/edu_quest.png"
  adaptive_icon_background: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/
